# 30.7 Gérer les `exceptions`



## Block `Try & Catch`

```cs
app.MapGet("/student", (IStudentRepo db) => {
    try
    {
        app.Logger.LogInformation("Fetching all the students from the storage");

        var students = db.GetAll();

        app.Logger.LogInformation($"Retourning {students.Count} students");

        return Results.Ok(students);
    }
    catch (Exception ex)
    {
        
        app.Logger.LogError($"Something went wrong: {ex.Message}");
        return Results.Problem("Data cause problem");
    }
});
```

Si je lance une `exception` j'obtiens :

<img src="assets/problem-results-builtin-message.png" alt="problem-results-builtin-message" style="zoom:50%;" />

On voit un `object error builtin` avec le `status code` et le message `detail` passé à `Results.Problem`.





## `UseExceptionHandler`

On peut aussi utiliser ce `builtin middleware` pour gérer proprement ses `exceptions`.



### `UseExceptionHandler(string errorHandlingPath)`

On passe simplement un chemin vers un `endpoint` gérant les `exceptions`.

```cs
app.UseExceptionHandler("/error");

app.MapGet("/error", () => Problem());
```

<img src="assets/error-builtin-problem-return.png" alt="error-builtin-problem-return" style="zoom: 25%;" />

Le même message est renvoyé quelque soit l'`exception`.

C'est une bonne réponse en mode `Production`.

Dans le même scénario, on peut créer une réponse plus complète pour le mode `Development` :

```cs
if(app.Environment.IsProduction())
{
    app.UseExceptionHandler("/error");
}

if(app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/error-dev");
}
```



```cs
app.MapGet("/error-dev", (IHostEnvironment environment, HttpContext context) => {
    Console.WriteLine($"environment: {environment.EnvironmentName}");

    var exceptionHandlerFeature = context.Features.Get<IExceptionHandlerFeature>();

    return Problem(
        detail: exceptionHandlerFeature?.Error.StackTrace,
        title: exceptionHandlerFeature?.Error.Message
    );
});
```

> On utilise les `Features` contenu dans `HttpContext.Features`. C'est une collection de paire `Type - Instance`.
>
> On peut aussi recevoir l'`environment` du conteneur de service avec `IHostEnvironment enbironment`.



### Utiliser l'`overload` :

### '`UseExceptionHandler(Action<IApplicationBuilder> configure)`

On créé une classe `ErrorDetails`

```cs
public class ErrorDetails
{
    public int StatusCode { get; set; }
    public string Message { get; set; } = string.Empty;

    public override string ToString()
    {
        return JsonSerializer.Serialize(this);
    }
}
```

ou un `record`:

```cs
public record ErrorDetail(
    string Title,
    string Type, 
    string Detail, 
    int StatusCode
);
```

> La méthode `Response.WriteAsJsonAsync` s'occupe de sérilizer pour nous. Pas besoin d'`overloader` la méthode `ToString`.

```cs
app.UseExceptionHandler((IApplicationBuilder appError) => {
    appError.Run(async context => {
        context.Response.ContentType = "application/json";
        context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;

        var exceptionHandlerFeature = context.Features.Get<IExceptionHandlerFeature>();

        await context.Response.WriteAsJsonAsync(new ErrorDetail(
            Title: exceptionHandlerFeature!.Error.Message,
            Type: exceptionHandlerFeature.Error.GetType()!.FullName!,
            Detail: exceptionHandlerFeature.Error.StackTrace!,
            StatusCode: context.Response.StatusCode
        ));
    });
});
```

> `Run(RequestDelegate handler)` ajoute un `terminal middleware`.
>
> Quelques `!` sont nécessaires pour affirmer que ce que l'on écrit ne peut pas être `null` (j'espère !!).



### Utilisation d'une `Extension Method`

On va créer une méthode d'extension `ExceptionMiddlewareExtension`

```cs
public static class ExceptionMiddlewareExtension
{
    public static void ConfigureExceptionHandler(this WebApplication app)
    {
        app.UseExceptionHandler(appError => {
            appError.Run(async context => {
                context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                context.Response.ContentType = "application/json";
                
                var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
                if(contextFeature is not null)
                {
                    app.Logger.LogError($"Something went wrong: {contextFeature.Error}");
                    
                    await context.Response.WriteAsync(new ErrorDetails {
                        StatusCode = context.Response.StatusCode,
                        Message = "Boum Boum !!!"
                    }.ToString());
                }
            });
        });
    }
}
```

> ### `HttpContext.Features`
>
> La propriété `Features` de `HttpContext` donne accès à une collection d'interface de fonctionnalités pour la requête courante. Ces fonctionnalités (`Features`) sont `mutables`, on peut les ajouter, les modifier, les étendre (`wrapped`), les remplacer ou aussi les supprimer.
>
> On y a ccès dans les `middleware`.
>
> C'est une collection avec des paires `Type-Instance`.
>
> Il existe des `getter` et des `setter` : `TFeature Get<TFeature>()` et `Set<TFeature>(TFeature instance)`.

On ajoute notre méthode d'extension dans `Program.cs`:

```cs
app.ConfigureExceptionHandler();
```

On peut retirer le block `Try & Catch` de notre `endpoint` :

```cs
app.MapGet("/student", (IStudentRepo db) =>
{
    app.Logger.LogInformation("Fetching all the students from the storage");

    var students = db.GetAll();

    throw new Exception("Hey you I'm an exception !!");

    app.Logger.LogInformation($"Retourning {students.Count} students");

    return Results.Ok(students);
});
```

<img src="assets/with-builtin-middleware-exception-handling.png" alt="with-builtin-middleware-exception-handling" style="zoom:50%;" />



## `Custom Middleware`

On va créer une classe `middleware` pour intercepter et gérer nos `exceptions`:

`ExceptionMiddleware`

```cs
public static class ExceptionMiddleware
{
    private readonly ILogger _logger;
    private readonly RequestDelegate _next;

    public ExceptionMiddleware(ILogger<ExceptionMiddleware> logger, RequestDelegate next)
    {
        _logger = logger;
        _next = next;
    }
    
    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (Exception ex)
        {
            _logger.LogError($"Something wrong in custom middleware {ex}");
            await HandleExceptionAsync(context);
        }
    }

    private Task HandleExceptionAsync(HttpContext context)
    {
        context.Response.ContentType = "application/json";
        context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
        
        return context.Response.WriteAsync(new ErrorDetails {
            StatusCode = context.Response.StatusCode,
            Message = "Boum boum boum !!!"
        }.ToString());
    }
}
```

On `log` l'`exception` mais on ne renvoie pas son message dans l'`api`.

On créé une méthode d'extension dans `ExceptionMiddlewareExtension` :

```cs
public static class ExceptionMiddlewareExtension
{
    // ...ConfigureExceptionHandler
    
    public static void ConfigureCustomExceptionMiddleware(this IApplicationBuilder app)
    {
        app.UseMiddleware<ExceptionMiddleware>();
    }
```

Et on l'utilise dans `Program.cs`:

```cs
//app.ConfigureExceptionHandler();
app.ConfigureCustomExceptionMiddleware();
```

> Il ne faut pas oublier de typer `ILogger` : `ILogger<ExceptionMiddleware>` sinon le `service` n'est pas résolu (trouvé).

<img src="assets/custom-middleware-third-exemple-works-fine.png" alt="custom-middleware-third-exemple-works-fine" style="zoom:50%;" />



## Gérer des types différents d'`Exception`

```cs
public class ExceptionHandlingMiddleware
{
    private readonly RequestDelegate _next;

    public ExceptionHandlingMiddleware(RequestDelegate next)
    {
        _next = next;
    }
    
    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (DomainNotFoundException ex)
        {
            context.Response.StatusCode = (int)HttpStatusCode.NotFound;
            await context.Response.WriteAsync(ex.Message);
        }
        catch (ApplicationInternalException ex)
        {
            context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            await context.Response.WriteAsync(ex.Message);
        }
        catch (Exception ex)
        {
            context.Response.StatusCode = (int)HttpStatusCode.ServiceUnavailable;
            await context.Response.WriteAsync(ex.Message);
        }
    }
}
```

On finit par les `Exception` générique.

